- name: Launch instances
  local_action:
    module: gce
    instance_names: "{{ names }}"
    machine_type: "{{ type }}"
    image: "{{ image }}"
    zone: "{{ zone }}"
    project_id: "{{ project_id }}"
    pem_file: "{{ pem_file }}"
    service_account_email: "{{ service_account_email }}"
    tags: "{{ tags }}"
    # preemptible: "{{ preemptible }}"
  register: gce
- name: Wait for SSH to be available
  local_action: wait_for host={{ item.public_ip }} port=22
                delay=20 timeout=30 state=started
  with_items: gce.instance_data
- name: Get hostname and add host
  local_action: add_host hostname={{ item.public_ip }}
                groupname=new_instances
  with_items: gce.instance_data
