- name: Install apache
  apt: pkg=apache2 state=present update_cache=yes
- name: custom healthstatus
  copy: dest=/var/www/isup.html content='ALIVE'
- name: set file stats on healthstatus
  file: path=/var/www/isup.html owner=root group=root mode=0644
- name: Install Python-Passlib package
  apt: pkg={{ item }} state=present
  with_items:
   - python-passlib
  when:
    - basic_auth_pass is defined
    - basic_auth_name is defined
- name: Setting Basic Authentication
  htpasswd: path=/var/www/.htpasswd name={{ basic_auth_name }} password={{ basic_auth_pass }} owner=root group=www-data mode=0640
  when:
    - basic_auth_pass is defined
    - basic_auth_name is defined
- name: Enabled mod-rewrite, mod-headers
  file: src=../mods-available/{{ item }}.load dest=/etc/apache2/mods-enabled/{{ item }}.load owner=root group=root state=link force=yes
  with_items:
    - rewrite
    - headers
- name: Remove apache2 conf
  command: removes=/etc/apache2/sites-available/default rm /etc/apache2/sites-available/default
  when:
    - basic_auth_pass is defined
    - basic_auth_name is defined
- name: Copy apache2 conf
  template: src=default.conf dest=/etc/apache2/sites-available/default
  notify:
    - restart apache
  when:
    - basic_auth_pass is defined
    - basic_auth_name is defined
