- name: Create two new GCE instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - "vars/target_wp.yml"
    - "vars/gce_auth.yml"
  tasks:
    - name: Launch instances
      local_action:
        module: gce
        instance_names: "{{ names }}"
        machine_type: "{{ type }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        project_id: "{{ project_id }}"
        pem_file: "{{ pem_file }}"
        service_account_email: "{{ service_account_email }}"
        tags: webserver
      register: gce
    - name: Wait for SSH to be available
      local_action: wait_for host={{ item.public_ip }} port=22
                    delay=20 timeout=30 state=started
      with_items: gce.instance_data
    - name: Get hostname and add host
      local_action: add_host hostname={{ item.public_ip }}
                    groupname=new_instances
      with_items: gce.instance_data

- name: Set Time Zone and Locale
  hosts: new_instances
  sudo: yes
  roles:
    - timezone_locale
    - git

- name: Setting Wordpress and Friends
  hosts: new_instances
  sudo: yes
  roles:
    - wordpress

- name: Create a firewall rule to allow HTTP
  hosts: localhost
  gather_facts: no
  vars_files:
    - "vars/gce_auth.yml"
  tasks:
    - name: Allow HTTP
      local_action:
        module: gce_net
        fwname: all-http
        name: default
        allowed: tcp:80
        service_account_email: "{{ service_account_email }}"
        pem_file: "{{ pem_file }}"
        project_id: "{{ project_id }}"
