- name: Set timezone variables
  copy: content='{{ timezone_name }}'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
  notify:
    - update timezone
- name: update Locale
  locale_gen: name={{ locale_name }} state=present
